### ISSUE TITLE
TypeError: Cannot set property 'isKeyword' of undefined

### ISSUE THREAD

**Issue by keirlawson** [tststs/atom-ternjs#103]
I'm getting the following error when I try to type ina variable declaration:

```
TypeError: Cannot set property 'isKeyword' of undefined at /home/keir/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:707:59 at gather (/home/keir/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:645:49) at /home/keir/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:707:9 at Array.forEach (native) at Object.findCompletions [as run] (/home/keir/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:706:45) at run (/home/keir/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:212:30) at Object.exports.withContext (/home/keir/.atom/packages/atom-ternjs/node_modules/tern/lib/infer.js:767:18) at /home/keir/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:219:13 at analyzeAll (/home/keir/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:333:15) at doRequest (/home/keir/.atom/packages/atom-ternjs/node_modules/tern/lib/tern.js:203:5)
```

**Comment by tststs** [comment]
@marijnh

**Comment by idmean** [comment]
I’m expiring this issue if I declare a variable between a `}` and a variable declaration. Example:

        if(err){
            //....
        }

       var fo //Typing foo shows the exception 

        var producers = [];

**Comment by tststs** [comment]
Please navigate to .atom/packages and
```
$ apm install
```
to update the node_modules. This should fix the problem.
This is also automatically done in the next release.

Thx @marijnh for the quick fix :)

**Comment by idmean** [comment]
No luck. I can still reproduce the problem with my example above.

**Comment by idmean** [comment]
Sorry, my mistake. Actually fixed the problem for me.

**Comment by tststs** [comment]
Should be fixed after updating to 0.7.1.
