### ISSUE TITLE
Uncaught TypeError: Cannot read property 'diffs' of undefined

### ISSUE THREAD

**Issue by satya164** [tststs/atom-ternjs#181]
**Update:** Also seems that this error occurs on every keystroke, just shown in the devtools. And the autocomplete doesn't work at all.

1. Click a variable
2. Atom Ternjs > Find references

### Tern config

```json
{
  "ecmaVersion": 6,
  "libs": [],
  "plugins": {
    "complete_strings": {},
    "doc_comment": {
      "fullDocs": true
    },
    "node": {},
    "modules": {},
    "es_modules": {}
  }
}
```

**Atom Version**: 1.3.1
**System**: Mac OS X 10.11.1
**Thrown From**: [atom-ternjs](https://github.com/tststs/atom-ternjs) package, v0.11.0

### Stack Trace

Uncaught TypeError: Cannot read property 'diffs' of undefined

```
At /Users/satya/.atom/packages/atom-ternjs/lib/atom-ternjs-client.coffee:39

TypeError: Cannot read property 'diffs' of undefined
    at Client.module.exports.Client.update (/Users/satya/.atom/packages/atom-ternjs/lib/atom-ternjs-client.coffee:39:42)
    at Reference.module.exports.Reference.findReference (/Users/satya/.atom/packages/atom-ternjs/lib/atom-ternjs-reference.coffee:48:21)
    at atom-text-editor.<anonymous> (/Users/satya/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:502:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1016:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:143:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:156:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:35.1.0 core:save (atom-text-editor.editor.is-focused)
  3x -1:32.4.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-behave-theme.theme-one-dark-ui)
     -1:10.5.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -1:10.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:10.4.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -1:10.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:03.0 grammar-selector:show (atom-text-editor.editor)
     -0:59.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:58.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:55.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:50.9.0 grammar-selector:show (atom-text-editor.editor)
     -0:48.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 12x -0:47.2.0 core:backspace (a.inline-block)
     -0:41.4.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:16.6.0 tern:definition (atom-text-editor.editor.is-focused)
     -0:05.4.0 tern:references (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "welcome",
      "ide-flow",
      "linter-flow"
    ],
    "themes": [
      "one-dark-ui",
      "behave-theme"
    ],
    "openEmptyEditorOnStart": false
  },
  "atom-ternjs": {
    "urls": false,
    "origins": false,
    "useSnippetsAndFunction": true,
    "displayAboveSnippets": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.19
atom-handlebars, v1.2.0
atom-ternjs, v0.11.0
atom-typescript, v7.14.2
atom-zurb-foundation, v1.1.1
auto-detect-indentation, v0.4.2
auto-reveal-in-sidebar, v0.8.0
auto-update-packages, v1.0.0
autoclose-html, v0.19.0
autocomplete-modules, v1.3.1
autocomplete-sass, v0.1.0
behave-theme, v1.6.0
change-case, v0.6.0
docblockr, v0.7.3
editorconfig, v1.2.2
file-type-icons, v0.7.4
highlight-line, v0.11.0
highlight-selected, v0.11.1
language-SCSS, v0.4.0
language-babel, v2.6.0
language-groovy, v0.4.0
linter, v1.11.3
linter-eslint, v5.2.6
linter-javac, v1.3.0
livereload, v0.4.4
open-recent, v4.0.1
pigments, v0.19.3
react, v0.12.10
sync-settings, v0.6.0
tabs-to-spaces, v1.0.1
term3, v0.19.2

# Dev
No dev packages
```

**Comment by nyrf** [comment]
Same issue, OSX 10.11.1, atom 1.4 beta0

**Comment by tststs** [comment]
Autocompletion currently isn't working until the files are registered via `loadEagerly`. Please refer to the README to set up your project. The next release will solve this issue.

**Comment by tststs** [comment]
problem should be solved.

**Comment by satya164** [comment]
@tststs May be the `README` should mention that autocomplete doesn't work without `loadEagerly`?

BTW this issue still seems to be happening.
