### ISSUE TITLE
atom-ternjs got slow?

### ISSUE THREAD

**Issue by Rukenshia** [tststs/atom-ternjs#59]
I updated to the latest version, i dont know how many i skipped though. If it helps, I know that the design of suggestions changed (and looks way better now). However, it feels like it is taking forever for the suggestions to come up now. I have a folder with several node modules (around 80 - 90 files in total) and its feeling a lot slower than before.

**Comment by tststs** [comment]
Please define "forever". Seconds?
My test suite eagerly loads around 60 files and the suggestion-list needs about 200ms to come up.
Indeed there is more computation done with the new version, but it shouldn't need forever.

Maybe you can post a profile, what takes so long.

Thx
tststs

**Comment by Rukenshia** [comment]
The following times are right after startup of atom, so nothing was cached before:

Getting suggestions of an object that is defined inside the same file (Typing 'MyObject.', then waiting): 8s
Getting suggestions of an object that is defined in the same package, different file: 2s
Getting suggestions of an global object in another package, same project: 4s

**Comment by tststs** [comment]
Ok, that's forever :)
But without a profile, it is impossible for me to help or fix anything.
I have some ideas, but i don't even know, if it is tern itself or the package. So i'm pretty lost.

A basic profile can be made with developer-tools -> view/developer/toggle developer tools and navigate to the profile tab.

Do a fresh startup, start profiling and stop profiling when the suggestion-list shows up.

Looks like this:
![bildschirmfoto 2015-04-10 um 18 45 35](https://cloud.githubusercontent.com/assets/3591665/7092392/cd65f3b6-dfb1-11e4-8825-41bc8267d736.png)

You may save the file and upload it. This would be great :)

Thx
tststs

**Comment by Rukenshia** [comment]
Here's the link: http://janchr.antares.uberspace.de/atom-ternjs.cpuprofile

**Comment by tststs** [comment]
hey, nothing atom-ternjs related in there (which seems pretty strange). could you please do the same for "timeline" with the option ```Js-Profiler``` activated. to save the result, you have to right-click the main thread in the result and save as. I'm pretty new to that, so maybe we both just figure out how we get the data we need :)


![bildschirmfoto 2015-04-10 um 22 02 37](https://cloud.githubusercontent.com/assets/3591665/7095765/545c9f94-dfcd-11e4-9ea4-aa208b5b80a6.png)


There is also an option called ```async callstack``` in the sources tab, which you might need to activate before recording:
located on the right top of the screenshot.

![bildschirmfoto 2015-04-10 um 22 03 58](https://cloud.githubusercontent.com/assets/3591665/7095806/a2438bbe-dfcd-11e4-89de-0e1b9db28238.png)
 
_________________________________

thx a lot :rocket: 
tststs

**Comment by Rukenshia** [comment]
When i try saving the timeline, atom crashes, only content in the timeline is '['.

**Comment by tststs** [comment]
@Haithembelhaj
@stffndtz

**Comment by Rukenshia** [comment]
So, I tried it today again and to get something that is more representing, I opened the node module "node-mysql" in Atom. I opened lib/Connection.js, started recording (CPU Profile, timeline didnt work again) and typed 'Connection.' in line 39. Took around 10 seconds before anything popped up. 

Link to the profile is same as above, I reuploaded the file: http://janchr.antares.uberspace.de/atom-ternjs.cpuprofile

**Comment by Rukenshia** [comment]
I just reinstalled my atom and now im not getting any suggestions at all, just a tern error:

```
C:\Users\Jan.atom\packages\atom-ternjs\node_modules\tern\lib\infer.js:1312 Obj.prototype.purge = function(test) { ^ RangeError: Maximum call stack size exceeded at Obj.purge (C:\Users\Jan.atom\packages\atom-ternjs\node_modules\tern\lib\infer.js:1312:33) 
at Fn.purge (C:\Users\Jan.atom\packages\atom-ternjs\node_modules\tern\lib\infer.js:1323:29) 
at Object.AVal.purge (C:\Users\Jan.atom\packages\atom-ternjs\node_modules\tern\lib\infer.js:1299:14) 
at Obj.purge (C:\Users\Jan.atom\packages\atom-ternjs\node_modules\tern\lib\infer.js:1319:10) 
at Object.AVal.purge (C:\Users\Jan.atom\packages\atom-ternjs\node_modules\tern\lib\infer.js:1299:14) 
at Object.AVal.purge (C:\Users\Jan.atom\packages\atom-ternjs\node_modules\tern\lib\infer.js:1307:11) 
at Object.AVal.purge (C:\Users\Jan.atom\packages\atom-ternjs\node_modules\tern\lib\infer.js:1307:11)
at Object.AVal.purge (C:\Users\Jan.atom\packages\atom-ternjs\node_modules\tern\lib\infer.js:1307:11) 
at Obj.purge (C:\Users\Jan.atom\packages\atom-ternjs\node_modules\tern\lib\infer.js:1319:10)
at Object.AVal.purge (C:\Users\Jan.atom\packages\atom-ternjs\node_modules\tern\lib\infer.js:1299:14)
```

**Comment by stffndtz** [comment]
I am looking into this today.

The error your seeing is from the tern.js package itself, it's a weird for-loop calling itself inside. This might be caused by returning too many properties and also might be the reason for it being so slow. But that's just a wild guess, I'll see if I can recreate the error and track down the origin.

**Comment by stffndtz** [comment]
I am looking into this today.

The error your seeing is from the tern.js package itself, it's a weird for-loop calling the function itself for every property. This might be caused by returning too many properties and also might be the reason for it being so slow. But that's just a wild guess, I'll see if I can recreate the error and track down the origin.

**Comment by stffndtz** [comment]
Here's a related issue also mentioning atom-ternjs:

https://github.com/marijnh/tern/issues/523

**Comment by Rukenshia** [comment]
Issue still isnt solved.

**Comment by Rukenshia** [comment]
And it's still not solved.

**Comment by SamVerschueren** [comment]
Think I might have the same issue. When I type ```function```, my atom freezes.

**Comment by Rukenshia** [comment]
Issue was closed on the ternjs repo, could you please update the tern version @tststs?

**Comment by tststs** [comment]
uninstall the package, restart atom and reinstall it - should do the trick :)
hope the issue is solved then. else let me know

**Comment by Rukenshia** [comment]
It's still not working. I've also updated the issue over at the tern repo again.

**Comment by Rukenshia** [comment]
Issue has somehow been resolved when I started my PC today.
